#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$ROOT_DIR/Weall-Protocol"
WEB_DIR="$ROOT_DIR/web"

BACKEND_VENV="${BACKEND_VENV:-$BACKEND_DIR/.venv}"
BACKEND_HOST="${BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${BACKEND_PORT:-8000}"

WEB_HOST="${WEB_HOST:-127.0.0.1}"
WEB_PORT="${WEB_PORT:-5173}"

say() { printf "\n\033[1m%s\033[0m\n" "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"; }
need_cmd python3
need_cmd node
need_cmd npm

[[ -d "$BACKEND_DIR" ]] || die "Backend dir not found: $BACKEND_DIR"
[[ -d "$WEB_DIR" ]] || die "Web dir not found: $WEB_DIR"

say "==> Backend: setup venv + install deps"
if [[ ! -d "$BACKEND_VENV" ]]; then
  python3 -m venv "$BACKEND_VENV"
fi

# shellcheck disable=SC1090
source "$BACKEND_VENV/bin/activate"
python -m pip install --upgrade pip wheel >/dev/null
python -m pip install -e "$BACKEND_DIR" >/dev/null

say "==> Web: install deps (npm ci)"
pushd "$WEB_DIR" >/dev/null
npm ci >/dev/null

say "==> Web: write .env.local (VITE_WEALL_API_BASE)"
cat > .env.local <<EOF
# Auto-generated by projects/dev_up.sh
VITE_WEALL_APP_NAME=WeAll
VITE_WEALL_ENV_LABEL=dev
VITE_WEALL_ENABLE_DEV_TOOLS=1
VITE_WEALL_API_BASE=http://${BACKEND_HOST}:${BACKEND_PORT}
VITE_WEALL_CLIENT_NAME=weall-web
VITE_WEALL_CLIENT_VERSION=0.1.0
EOF
popd >/dev/null

BACKEND_LOG="$ROOT_DIR/.dev_backend.log"
WEB_LOG="$ROOT_DIR/.dev_web.log"

BACKEND_PID=""
WEB_PID=""

cleanup() {
  say "==> Shutting down..."
  if [[ -n "${WEB_PID:-}" ]] && kill -0 "$WEB_PID" >/dev/null 2>&1; then
    kill "$WEB_PID" >/dev/null 2>&1 || true
  fi
  if [[ -n "${BACKEND_PID:-}" ]] && kill -0 "$BACKEND_PID" >/dev/null 2>&1; then
    kill "$BACKEND_PID" >/dev/null 2>&1 || true
  fi
  wait >/dev/null 2>&1 || true
  say "==> Done."
}
trap cleanup INT TERM EXIT

say "==> Starting backend (uvicorn, reload)"
(
  cd "$BACKEND_DIR"
  # shellcheck disable=SC1090
  source "$BACKEND_VENV/bin/activate"

  export WEALL_API_HOST="$BACKEND_HOST"
  export WEALL_API_PORT="$BACKEND_PORT"

  # Use uvicorn directly so host/port/reload are guaranteed.
  exec python -m uvicorn "weall.api.app:create_app" --factory --reload --host "$BACKEND_HOST" --port "$BACKEND_PORT"
) >"$BACKEND_LOG" 2>&1 &
BACKEND_PID="$!"

say "==> Starting web (vite)"
(
  cd "$WEB_DIR"
  exec npm run dev -- --host "$WEB_HOST" --port "$WEB_PORT"
) >"$WEB_LOG" 2>&1 &
WEB_PID="$!"

say "==> Services"
echo "Backend: http://${BACKEND_HOST}:${BACKEND_PORT}"
echo "Web:     http://${WEB_HOST}:${WEB_PORT}"
echo "Logs:"
echo "  - $BACKEND_LOG"
echo "  - $WEB_LOG"
say "==> Running (Ctrl+C to stop)"

# Supervisor loop
while true; do
  if ! kill -0 "$BACKEND_PID" >/dev/null 2>&1; then
    echo "Backend exited. Last 60 lines:" >&2
    tail -n 60 "$BACKEND_LOG" >&2 || true
    exit 1
  fi
  if ! kill -0 "$WEB_PID" >/dev/null 2>&1; then
    echo "Web exited. Last 60 lines:" >&2
    tail -n 60 "$WEB_LOG" >&2 || true
    exit 1
  fi
  sleep 1
done
