#!/usr/bin/env python3
"""Install a public WeAll node-operator onboarding bundle into a safe env file.

This installer is for normal node operators. It verifies the public onboarding
bundle, converts it into public-only shell exports, and writes those exports to a
local env file that can be sourced before running node/operator preflights.

It intentionally refuses to run when external identity-provider or authority-signer secrets are
present in the current environment, unless explicitly overridden for test/admin
contexts. It never writes node private key material.
"""
from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PROHIBITED_ENV_KEYS = [
    "WEALL_ORACLE_AUTHORITY_SIGNER_PRIVKEY",
    "WEALL_ORACLE_AUTHORITY_PRIVKEY",
    "WEALL_TRUSTED_AUTHORITY_PRIVKEYS",
]

PROHIBITED_OUTPUT_PATTERNS = [
    "WEALL_ORACLE_AUTHORITY_SIGNER_PRIVKEY",
    "WEALL_ORACLE_AUTHORITY_PRIVKEY",
    "WEALL_NODE_PRIVKEY=",
    "WEALL_NODE_PRIVKEY_FILE=",
    "PRIVATE_KEY",
    "PASSWORD",
]


def _fail(message: str) -> None:
    raise RuntimeError(message)


def _check_secret_boundary(*, allow_external_identity_secrets_present: bool) -> None:
    if allow_external_identity_secrets_present:
        return
    present = [key for key in PROHIBITED_ENV_KEYS if os.environ.get(key)]
    if present:
        _fail("external_identity_or_authority_secret_present:" + ",".join(sorted(present)))


def _run_verify(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "verify_node_operator_onboarding_bundle.py"), *args],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def _shell_quote_path(path: Path) -> str:
    raw = str(path)
    return "'" + raw.replace("'", "'\\''") + "'"


def _build_env_content(*, bundle: Path, manifest: Path) -> str:
    check = _run_verify([
        "--bundle",
        str(bundle),
        "--manifest",
        str(manifest),
        "--json",
    ])
    if check.returncode != 0:
        detail = (check.stdout or check.stderr or "bundle verification failed").strip()
        _fail("bundle_verification_failed:" + detail)

    emit = _run_verify([
        "--bundle",
        str(bundle),
        "--manifest",
        str(manifest),
        "--emit-shell-env",
    ])
    if emit.returncode != 0:
        detail = (emit.stdout or emit.stderr or "bundle env export failed").strip()
        _fail("bundle_env_export_failed:" + detail)

    exports = emit.stdout.strip()
    for pattern in PROHIBITED_OUTPUT_PATTERNS:
        if pattern in exports:
            _fail("unsafe_export_contains_secret_like_pattern:" + pattern)

    header = [
        "# WeAll node-operator public onboarding environment",
        "# Generated by scripts/install_node_operator_onboarding_bundle.py",
        "# This file contains public chain authority anchors only.",
        f"export WEALL_NODE_OPERATOR_ONBOARDING_BUNDLE={_shell_quote_path(bundle)}",
        f"export WEALL_CHAIN_MANIFEST_PATH={_shell_quote_path(manifest)}",
        "export WEALL_REQUIRE_CHAIN_MANIFEST=1",
    ]
    return "\n".join(header) + "\n" + exports + "\n"


def _install(args: argparse.Namespace) -> Path:
    bundle = Path(args.bundle).expanduser().resolve()
    manifest = Path(args.manifest).expanduser().resolve()
    out = Path(args.out).expanduser().resolve()

    if not bundle.is_file():
        _fail(f"bundle_not_found:{bundle}")
    if not manifest.is_file():
        _fail(f"manifest_not_found:{manifest}")
    _check_secret_boundary(allow_external_identity_secrets_present=bool(args.allow_external_identity_secrets_present))

    content = _build_env_content(bundle=bundle, manifest=manifest)
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists() and not args.force:
        _fail(f"output_exists:{out}: pass --force to overwrite")
    out.write_text(content, encoding="utf-8")
    os.chmod(out, stat.S_IRUSR | stat.S_IWUSR)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Install a public WeAll node-operator onboarding bundle.")
    parser.add_argument("--bundle", required=True, help="Path to node-operator onboarding bundle JSON")
    parser.add_argument(
        "--manifest",
        default=str(ROOT / "configs" / "chains" / "weall-genesis.json"),
        help="Expected chain manifest to verify against",
    )
    parser.add_argument("--out", default=".weall-node-operator.env", help="Env file to write")
    parser.add_argument("--force", action="store_true", help="Overwrite existing output file")
    parser.add_argument(
        "--allow-external-identity-secrets-present",
        action="store_true",
        help="Allow installation even if external identity-provider/admin secrets are present in the current environment",
    )
    parser.add_argument("--print-source-command", action="store_true")
    args = parser.parse_args()

    try:
        out = _install(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.print_source_command:
        print(f"source {_shell_quote_path(out)}")
    else:
        print(str(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
