#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from weall.runtime.bootstrap_manifest import (  # noqa: E402
    canon_json,
    load_json_object,
    read_db_state,
    build_anchor_from_state,
    verify_anchor,
    validator_epoch_and_hash,
    expected_startup_fingerprint,
    verify_local_manifest,
    release_pubkey,
    verify_manifest_integrity,
)
from weall.runtime.chain_config import load_chain_config, production_bootstrap_report  # noqa: E402
from weall.runtime.protocol_profile import PRODUCTION_CONSENSUS_PROFILE  # noqa: E402


def _sha256_file(path: Path) -> str:
    import hashlib

    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            chunk = fh.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify local validator bootstrap invariants against tx index, protocol profile, DB state, and optional trusted anchor or bundle.")
    parser.add_argument("--db-path", default=None, help="Path to node SQLite DB. Defaults to chain config db_path.")
    parser.add_argument("--tx-index-path", default=None, help="Path to generated tx index. Defaults to chain config tx_index_path.")
    parser.add_argument("--anchor", default=None, help="Optional path to trusted anchor JSON.")
    parser.add_argument("--bundle", default=None, help="Optional path to a bootstrap bundle JSON generated by build_validator_bootstrap_bundle.py.")
    parser.add_argument("--release-pubkey", default=None, help="Release manifest signer Ed25519 public key. Defaults to WEALL_RELEASE_PUBKEY/FILE.")
    parser.add_argument("--json", action="store_true", help="Emit compact JSON instead of pretty text.")
    args = parser.parse_args()

    cfg = load_chain_config()
    db_path = Path(args.db_path or cfg.db_path).resolve()
    tx_index_path = Path(args.tx_index_path or cfg.tx_index_path).resolve()
    bundle_path = Path(args.bundle).resolve() if args.bundle else None
    anchor_path = Path(args.anchor).resolve() if args.anchor else None
    issues: list[str] = []

    try:
        state, meta = read_db_state(db_path)
    except Exception as exc:
        report = {"ok": False, "issues": [f"failed to read db state: {exc}"], "db_path": str(db_path)}
        print(canon_json(report) if args.json else json.dumps(report, indent=2, sort_keys=True))
        return 1

    tx_index_hash = _sha256_file(tx_index_path) if tx_index_path.is_file() else ""
    schema_version = str(meta.get("schema_version") or ((state.get("meta") or {}) if isinstance(state.get("meta"), dict) else {}).get("schema_version") or "1")
    validator_epoch, validator_set_hash_value, normalized_validators = validator_epoch_and_hash(state)
    observed_anchor = build_anchor_from_state(state)

    try:
        expected_anchor = load_json_object(anchor_path, kind="trusted anchor")
    except Exception as exc:
        issues.append(f"failed to load trusted anchor: {exc}")
        expected_anchor = None
    issues.extend(verify_anchor(expected=expected_anchor, observed=observed_anchor))

    expected_fp = expected_startup_fingerprint(
        cfg_chain_id=str(cfg.chain_id or ""),
        cfg_node_id=str(cfg.node_id or ""),
        tx_index_hash=tx_index_hash,
        schema_version=schema_version,
        validator_epoch=validator_epoch,
        validator_set_hash_value=validator_set_hash_value,
    )

    bundle_report = None
    bundle_integrity = None
    if bundle_path is not None:
        bundle_integrity = verify_manifest_integrity(load_json_object(bundle_path, kind="bootstrap bundle") or {})
        bundle_report = verify_local_manifest(
            cfg=cfg,
            manifest_path=bundle_path,
            expected_pubkey=str(args.release_pubkey or release_pubkey() or "").strip(),
        )
        issues.extend(list(bundle_report.get("issues") or []))
        try:
            bundle = load_json_object(bundle_path, kind="bootstrap bundle")
        except Exception:
            bundle = None
    else:
        bundle = None

    report = {
        "ok": not issues,
        "chain_id": str(cfg.chain_id or ""),
        "db_path": str(db_path),
        "tx_index_path": str(tx_index_path),
        "schema_version": schema_version,
        "protocol_profile": PRODUCTION_CONSENSUS_PROFILE.to_json(),
        "protocol_profile_hash": PRODUCTION_CONSENSUS_PROFILE.profile_hash(),
        "tx_index_hash": tx_index_hash,
        "db_meta": {
            "chain_id": str(meta.get("chain_id") or ""),
            "schema_version": str(meta.get("schema_version") or ""),
            "production_consensus_profile_hash": str(meta.get("production_consensus_profile_hash") or ""),
            "tx_index_hash": str(meta.get("tx_index_hash") or ""),
        },
        "validator_epoch": validator_epoch,
        "validator_set_hash": validator_set_hash_value,
        "normalized_validators": normalized_validators,
        "startup_fingerprint": {
            "expected": expected_fp,
            "bundle": (bundle.get("startup_fingerprint") if isinstance(bundle, dict) else None),
        },
        "trusted_anchor": {
            "expected": expected_anchor,
            "bundle": (bundle.get("trusted_anchor") if isinstance(bundle, dict) else None),
            "observed": observed_anchor,
        },
        "bundle_integrity_issues": bundle_integrity,
        "release_manifest": bundle_report,
        "bootstrap_report": production_bootstrap_report(cfg),
        "issues": issues,
    }

    if args.json:
        print(canon_json(report))
    else:
        print(json.dumps(report, indent=2, sort_keys=True))
        if issues:
            print("\nBootstrap verification failed:")
            for item in issues:
                print(f"- {item}")
        else:
            print("\nBootstrap verification passed.")
    return 0 if not issues else 1


if __name__ == "__main__":
    raise SystemExit(main())
